name: WML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    name: Verify WML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update >/dev/null
          sudo apt-get upgrade -y >/dev/null
          sudo apt-get install -y enchant-2 hunspell hunspell-en-us
          pip install pyenchant~=3.0
      - name: Run wmllint
        run: |
          exec 5>&1
          if [[ -n $(python data/tools/wmllint -d data/ 2>&1 | grep --line-buffered "^[^#].*" | tee >(cat - >&5)) ]]; then
            echo "Found issues detected by wmllint."
            exit 1
          fi
      - name: Run wmlindent
        run: |
          exec 5>&1
          if [[ -n $(python data/tools/wmlindent -d data/ 2>&1 | grep --line-buffered "^[^#].*" | tee >(cat - >&5)) ]]; then
            echo "Found issues detected by wmlindent."
            exit 1
          fi
        if: always()
      - name: Run wmlscope
        run: |
          exec 5>&1
          if [[ -n $(python data/tools/wmlscope data/ 2>&1 | grep --line-buffered "^[^#].*" | tee >(cat - >&5)) ]]; then
            echo "Found issues detected by wmlscope."
            exit 1
          fi
        if: always()
